name: CD

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  publish-release_assets:
    name: Publish the release assets
    runs-on: ubuntu-latest
    needs: [build-distrod_wsl_launcher]

    steps:
      - uses: actions/checkout@v2

      - name: Get the arch name
        run: |
          echo "ARCH_NAME=aarch64" >> $GITHUB_ENV

      - name: Download opt_distrod
        uses: actions/download-artifact@v2
        with:
          name: "opt_distrod-${{ env.ARCH_NAME }}"
          path: assets

      - name: Download distrod_wsl_launcher
        uses: actions/download-artifact@v2
        with:
          name: "distrod_wsl_launcher-${{ env.ARCH_NAME }}"
          path: "distrod_wsl_launcher-${{ env.ARCH_NAME }}"

      - name: Zip distrod_wsl_launcher
        run: |
          sudo apt update
          sudo apt install -y zip
          zip -r "distrod_wsl_launcher-${{ env.ARCH_NAME }}.zip" "distrod_wsl_launcher-${{ env.ARCH_NAME }}"
          mv "distrod_wsl_launcher-${{ env.ARCH_NAME }}.zip" assets/

      - name: Read the commit message and use it as a body of the new release
        shell: bash
        run: |
          release="$(git log $(echo ${{ github.ref }} | grep -o 'v.*') -1 --pretty=format:%B)"  # Use the commit message as the release message
          echo "RELEASE_BODY<<EOF" >> $GITHUB_ENV
          echo "$release" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Upload Binaries to Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: assets/*
          file_glob: true
          tag: ${{ github.ref }}
          overwrite: true
          body: |
            ${{ env.RELEASE_BODY }}

  build-distrod_wsl_launcher:
    name: Build Distrod WSL launcher
    runs-on: windows-latest
    needs: [build-distrod-command]

    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            distrod/target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Get the arch name
        shell: bash
        run: |
          echo "ARCH_NAME=aarch64" >> $GITHUB_ENV

      - name: Download the Distrod's rootfs
        uses: actions/download-artifact@v2
        with:
          name: "distrod_root-${{ env.ARCH_NAME }}"
          path: rootfs

      - name: Build
        run: make -f windows.mk ROOTFS_PATH=rootfs/distrod_root.tar.gz distrod_wsl_launcher

      - name: Upload for the assets
        uses: actions/upload-artifact@v2
        with:
          name: "distrod_wsl_launcher-${{ env.ARCH_NAME }}"
          path: distrod/target/release/distrod_wsl_launcher.exe
          if-no-files-found: error

  build-distrod-command:
    name: Build distrod Linux command
    runs-on: ubuntu-latest

    needs: [build-portproxy-exe]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            distrod/target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Get the arch name
        shell: bash
        run: |
          echo "ARCH_NAME=aarch64" >> $GITHUB_ENV

      - name: Download portproxy.exe
        uses: actions/download-artifact@v2
        with:
          name: "portproxy-${{ env.ARCH_NAME }}"
          path: distrod/target/release

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get upgrade
          sudo apt-get install -y patchelf apt-file gcc-10 gcc-10-aarch64-linux-gnu
          sudo apt-file update

          sudo ln -sf /bin/gcc-10 /bin/gcc
          sudo ln -sf /bin/aarch64-linux-gnu-gcc-10 /bin/aarch64-linux-gnu-gcc

          rustup self update
          rustup target add aarch64-unknown-linux-gnu
          printf "deb [arch=arm64] http://ports.ubuntu.com/ubuntu-ports/ focal main restricted universe multiverse\ndeb [arch=arm64] http://ports.ubuntu.com/ubuntu-ports/ focal-updates main restricted universe multiverse\ndeb [arch=arm64] http://ports.ubuntu.com/ubuntu-ports/ focal-backports main restricted universe multiverse\ndeb [arch=arm64] http://ports.ubuntu.com/ubuntu-ports/ focal-security main restricted universe multiverse" | sudo tee -a /etc/apt/sources.list
          printf '[build]\ntarget = "aarch64-unknown-linux-gnu"\n\n[target.aarch64-unknown-linux-gnu]\nlinker = "/usr/bin/aarch64-linux-gnu-gcc-10"\n\n[target.x86_64-unknown-linux-gnu]\nlinker = "/usr/bin/gcc-10"' > $HOME/.cargo/config.toml

          sudo dpkg --add-architecture arm64
          sudo apt update && sudo apt install -y pkg-config libssl-dev:arm64 libssl-dev:amd64
          
      - name: Build the Distrod command
        run: PKG_CONFIG_SYSROOT_DIR=/usr/aarch64-linux-gnu/ make distrod-release

      - name: Build the Distrod rootfs
        run: make OUTPUT_ROOTFS_PATH=distrod_root.tar.gz rootfs

      - name: Upload opt_distrod.tar.gz for the assets
        uses: actions/upload-artifact@v2
        with:
          name: "opt_distrod-${{ env.ARCH_NAME }}"
          path: opt_distrod.tar.gz
          if-no-files-found: error

      - name: Upload distrod_root.tar.gz for the Windows build
        uses: actions/upload-artifact@v2
        with:
          name: "distrod_root-${{ env.ARCH_NAME }}"
          path: distrod_root.tar.gz
          if-no-files-found: error

  build-portproxy-exe:
    name: Build portproxy.exe
    runs-on: windows-2022

    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            distrod/target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Get the arch name
        shell: bash
        run: |
          echo "ARCH_NAME=aarch64" >> $GITHUB_ENV

      - name: Prepare build
        run: |
          rustup target install aarch64-pc-windows-msvc
          cwd=$(pwd)
          cd "/c/Program Files/Microsoft Visual Studio"
          cd $(ls -d */|head -n 1)
          cd $(ls -d */|head -n 1)
          cd VC/Tools/MSVC/
          cd $(ls -d */|head -n 1)
          arm64Link=$(pwd)/bin/Hostx64/arm64/link.exe
          x64Link=$(pwd)/bin/Hostx64/x64/link.exe
          printf '[build]\ntarget = "aarch64-pc-windows-msvc"\n\n[target.aarch64-pc-windows-msvc]\nlinker = "%s"\n\n[target.x86_64-pc-windows-msvc]\nlinker = "%s"' "$arm64Link" "$x64Link" > $HOME/.cargo/config.toml
          cd $cwd
          
      - name: Build
        run: make -f windows.mk portproxy.exe

      - name: Upload portproxy.exe for the Linux build
        uses: actions/upload-artifact@v2
        with:
          name: "portproxy-${{ env.ARCH_NAME }}"
          path: distrod/target/release/aarch64-pc-windows-msvc/portproxy.exe
          if-no-files-found: error
